include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
    - 'lib/generated/**'

linter:
  rules:
    public_member_api_docs: false
