name: food_app
version: 1.0.0+1
publish_to: none
description: UI food app
environment: 
  sdk: '>=3.0.0-366.0.dev <4.0.0'
dependencies: 
  auto_route: ^7.7.0
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^15.1.0+1
  freezed_annotation: ^2.4.1
  http: ^0.13.6
  intl: ^0.18.0
  json_annotation: ^4.8.1
  overlay_support: ^2.1.0
  path_provider: ^2.0.15
  retrofit: '>=4.0.0 <5.0.0'
  shimmer: ^3.0.0
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
dev_dependencies: 
  auto_route_generator: ^7.2.0
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  pubspec_dependency_sorter: ^1.0.3
  retrofit_generator: '>=5.0.0 <6.0.0'
  very_good_analysis: ^5.0.0+1
  flutter_test: 
    sdk: flutter
flutter: 
  assets: 
    - assets/images/location.png
    - assets/images/bag.png
    - assets/images/home.png
    - assets/images/profile_circle.png
    - assets/images/search_normal.png
    - assets/images/back_button.png
    - assets/images/favorite.png
    - assets/images/close.png
    - assets/images/profile.jpeg
  uses-material-design: true
flutter_intl: 
  enabled: true
