name: food_app
description: UI food app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0-366.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  json_annotation: ^4.8.1
  http: ^0.13.6
  freezed_annotation: ^2.4.1
  shimmer: ^3.0.0
  intl: ^0.18.0
  retrofit: ">=4.0.0 <5.0.0"
  dio: ^5.2.1+1
  bloc: ^8.1.2
  auto_route: ^7.7.0
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  overlay_support: ^2.1.0
  path_provider: ^2.0.15

dev_dependencies:
  auto_route_generator: ^7.2.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  retrofit_generator: ">=5.0.0 <6.0.0"
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/location.png
    - assets/images/bag.png
    - assets/images/home.png
    - assets/images/profile_circle.png
    - assets/images/search_normal.png
    - assets/images/back_button.png
    - assets/images/favorite.png
    - assets/images/close.png
    - assets/images/profile.jpeg

flutter_intl:
  enabled: true
